### ISSUE TITLE
Header verification takes too much time that cuses the header adding delay.

### ISSUE THREAD

**Issue by shekohex** [edgeware-builders/substrate-eth-light-client#15]
There is an issue where we try to add a new header to the `Headers` map, to do so, we query the Headers map for `parent_hash` of the new header we try to add.
if the parent header exists, we get it and start verification. sounds simple?

the real issue is that the verification process takes much more time than it should, since the next header panics when it tries to be added because its parent is not there yet! (its parent header is still in the verification process.)

**Comment by drewstone** [comment]
This is a bit odd because I would assume that txes should finish before the next TX is processed.

**Comment by shekohex** [comment]
what I suggest is using two different header storage:
one for unverified headers where everything goes here without the verification step, and another one originally for the verified headers and the header would get moved from the unverified headers to the verified ones.

that way the verification process can work freely.
I'm not sure if this the most efficient way to do so and solving this issue.
any thoughts?

**Comment by shekohex** [comment]
false alarm, it was how we parse and use the headers that caused the wrong `mix_hash` and other issues.
